# Generated by Django 3.2.4 on 2021-06-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
