# Generated by Django 3.2.4 on 2021-06-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20210605_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nDocumento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('password', models.CharField(max_length=15, verbose_name='Clave')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Direccion')),
                ('calle', models.CharField(max_length=30, verbose_name='Nombre Calle')),
                ('tipoVivienda', models.CharField(max_length=15, verbose_name='Casa o Depto')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero o Letra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
