# Generated by Django 3.2.4 on 2021-06-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comentario_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='coment',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idComentario',
            field=models.IntegerField(null=True, primary_key=True, serialize=False, verbose_name='Id Comentario'),
        ),
    ]
