# Generated by Django 3.2.4 on 2021-06-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210610_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='direccion',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tienda'),
        ),
    ]
