# Generated by Django 3.2.4 on 2021-06-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210610_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='tienda',
        ),
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ciudad'),
        ),
    ]
