# Generated by Django 3.2.4 on 2021-06-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ciudad_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nDocumento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('password', models.CharField(max_length=15, verbose_name='Clave')),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='user',
        ),
        migrations.RenameModel(
            old_name='TipoUsuario',
            new_name='Tipous',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='persona',
            name='tipous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipous'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
    ]
