# Generated by Django 3.2.4 on 2021-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tienda_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=15, null=True, verbose_name='Talla'),
        ),
    ]
