# Generated by Django 3.2.4 on 2021-07-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_producto_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='password',
        ),
    ]
