# Generated by Django 3.2.4 on 2021-06-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ndocumento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno de Usuario')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno de Usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo del Usuario')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono del Usuario')),
                ('clave', models.CharField(max_length=15, verbose_name='Clave del Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Direccion')),
                ('calle', models.CharField(max_length=50, verbose_name='Nombre de la Calle')),
                ('vivienda', models.CharField(max_length=15, verbose_name='Definir Casa o Depto y el numero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
