# Generated by Django 3.2.4 on 2021-06-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('iddireccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Direccion')),
                ('calle', models.CharField(max_length=50, verbose_name='Nombre de la Calle')),
                ('vivienda', models.CharField(max_length=15, verbose_name='Definir Casa o Depto')),
                ('numero', models.CharField(max_length=10, verbose_name='Número de la Vivienda')),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.AddField(
            model_name='direcciones',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios'),
        ),
    ]
