# Generated by Django 3.2.4 on 2021-06-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210605_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno de Usuario')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno de Usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo del Usuario')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono del Usuario')),
                ('clave', models.CharField(max_length=15, verbose_name='Clave del Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Direcciones',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
