# Generated by Django 3.2.4 on 2021-06-06 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210605_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Direccion')),
                ('calle', models.CharField(max_length=50, verbose_name='Nombre de la Calle')),
                ('vivienda', models.CharField(max_length=15, verbose_name='Definir Casa o Depto')),
                ('numero', models.CharField(max_length=10, verbose_name='Número de la Vivienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
